name: Test

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install curl
        run: sudo apt-get install curl -y

      - name: Check Domain Connectivity
        run: |
          cat test_main.txt | while read -r line
          do
            echo "Checking connectivity to $line"
            curl --head --silent --fail $line
          done
